// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_HGxX5fafWt-vIIulCqHo1YVgID1DpAo',
    appId: '1:486696817785:web:dfe478e14ca4bbd70870a8',
    messagingSenderId: '486696817785',
    projectId: 'testproject-b1527',
    authDomain: 'testproject-b1527.firebaseapp.com',
    databaseURL: 'https://testproject-b1527-default-rtdb.firebaseio.com',
    storageBucket: 'testproject-b1527.appspot.com',
    measurementId: 'G-H7G4XD6N0N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDsTgj1SVvTSxM1VP8lh5H2wcYvSpSIvig',
    appId: '1:486696817785:android:2ff20c1a80f44ff40870a8',
    messagingSenderId: '486696817785',
    projectId: 'testproject-b1527',
    databaseURL: 'https://testproject-b1527-default-rtdb.firebaseio.com',
    storageBucket: 'testproject-b1527.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDr9UOmUMXB9ryoq5eF2L_TJdFOy_0ej6g',
    appId: '1:486696817785:ios:96e0a5a5af0b148c0870a8',
    messagingSenderId: '486696817785',
    projectId: 'testproject-b1527',
    databaseURL: 'https://testproject-b1527-default-rtdb.firebaseio.com',
    storageBucket: 'testproject-b1527.appspot.com',
    iosBundleId: 'com.example.firebasehassanclasscrud',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDr9UOmUMXB9ryoq5eF2L_TJdFOy_0ej6g',
    appId: '1:486696817785:ios:fc163b3a7663f4940870a8',
    messagingSenderId: '486696817785',
    projectId: 'testproject-b1527',
    databaseURL: 'https://testproject-b1527-default-rtdb.firebaseio.com',
    storageBucket: 'testproject-b1527.appspot.com',
    iosBundleId: 'com.example.firebasehassanclasscrud.RunnerTests',
  );
}
